name: Update GitHub IPs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-github-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch GitHub IPs
        run: |
          curl -sSL https://api.github.com/meta | jq . > github-ips.json

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet github-ips.json; then
            git add github-ips.json
            git commit -m "Update GitHub IPs"
            git push
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Get diff for issue
        if: env.CHANGED == 'true'
        id: getdiff
        run: |
          git show HEAD -- github-ips.json > diff.txt
          echo "DIFF<<EOF" >> $GITHUB_ENV
          cat diff.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create issue if IPs updated
        if: env.CHANGED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'GitHub IPs Updated',
              assignees: ['evanallen13'],
              body: 'The GitHub IPs have been updated and committed to github-ips.json.\n\nDiff:\n\n' + process.env.DIFF
            })
